package com.forestotzka.yurufu.slabee.datagen;

import com.forestotzka.yurufu.slabee.block.ModBlocks;
import com.mojang.datafixers.util.Pair;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricRecipeProvider;
import net.fabricmc.fabric.api.datagen.v1.recipe.FabricRecipeExporter;
import net.minecraft.block.Blocks;
import net.minecraft.data.recipe.RecipeExporter;
import net.minecraft.data.recipe.RecipeGenerator;
import net.minecraft.data.recipe.ShapedRecipeJsonBuilder;
import net.minecraft.item.Item;
import net.minecraft.item.ItemConvertible;
import net.minecraft.predicate.item.ItemPredicate;
import net.minecraft.recipe.RecipeInputProvider;
import net.minecraft.recipe.book.RecipeCategory;
import net.minecraft.registry.RegistryEntryLookup;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.util.Identifier;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.CompletableFuture;

import static net.minecraft.data.recipe.RecipeGenerator.*;

public class ModRecipeProvider extends FabricRecipeProvider {
    List<Pair<ItemConvertible, ItemConvertible>> slabs = Arrays.asList(
            /*new Pair<>(ModBlocks.OAK_LOG_SLAB, Blocks.OAK_LOG),
            new Pair<>(ModBlocks.SPRUCE_LOG_SLAB, Blocks.SPRUCE_LOG),
            new Pair<>(ModBlocks.BIRCH_LOG_SLAB, Blocks.BIRCH_LOG),
            new Pair<>(ModBlocks.JUNGLE_LOG_SLAB, Blocks.JUNGLE_LOG),
            new Pair<>(ModBlocks.ACACIA_LOG_SLAB, Blocks.ACACIA_LOG),
            new Pair<>(ModBlocks.DARK_OAK_LOG_SLAB, Blocks.DARK_OAK_LOG),
            new Pair<>(ModBlocks.MANGROVE_LOG_SLAB, Blocks.MANGROVE_LOG),
            new Pair<>(ModBlocks.CHERRY_LOG_SLAB, Blocks.CHERRY_LOG),
            new Pair<>(ModBlocks.BAMBOO_BLOCK_SLAB, Blocks.BAMBOO_BLOCK),
            new Pair<>(ModBlocks.CRIMSON_STEM_SLAB, Blocks.CRIMSON_STEM),
            new Pair<>(ModBlocks.WARPED_STEM_SLAB, Blocks.WARPED_STEM),
            new Pair<>(ModBlocks.OAK_WOOD_SLAB, Blocks.OAK_WOOD),
            new Pair<>(ModBlocks.SPRUCE_WOOD_SLAB, Blocks.SPRUCE_WOOD),
            new Pair<>(ModBlocks.BIRCH_WOOD_SLAB, Blocks.BIRCH_WOOD),
            new Pair<>(ModBlocks.JUNGLE_WOOD_SLAB, Blocks.JUNGLE_WOOD),
            new Pair<>(ModBlocks.ACACIA_WOOD_SLAB, Blocks.ACACIA_WOOD),
            new Pair<>(ModBlocks.DARK_OAK_WOOD_SLAB, Blocks.DARK_OAK_WOOD),
            new Pair<>(ModBlocks.MANGROVE_WOOD_SLAB, Blocks.MANGROVE_WOOD),
            new Pair<>(ModBlocks.CHERRY_WOOD_SLAB, Blocks.CHERRY_WOOD),
            new Pair<>(ModBlocks.CRIMSON_HYPHAE_SLAB, Blocks.CRIMSON_HYPHAE),
            new Pair<>(ModBlocks.WARPED_HYPHAE_SLAB, Blocks.WARPED_HYPHAE),
            new Pair<>(ModBlocks.STRIPPED_OAK_LOG_SLAB, Blocks.STRIPPED_OAK_LOG),
            new Pair<>(ModBlocks.STRIPPED_SPRUCE_LOG_SLAB, Blocks.STRIPPED_SPRUCE_LOG),
            new Pair<>(ModBlocks.STRIPPED_BIRCH_LOG_SLAB, Blocks.STRIPPED_BIRCH_LOG),
            new Pair<>(ModBlocks.STRIPPED_JUNGLE_LOG_SLAB, Blocks.STRIPPED_JUNGLE_LOG),
            new Pair<>(ModBlocks.STRIPPED_ACACIA_LOG_SLAB, Blocks.STRIPPED_ACACIA_LOG),
            new Pair<>(ModBlocks.STRIPPED_DARK_OAK_LOG_SLAB, Blocks.STRIPPED_DARK_OAK_LOG),
            new Pair<>(ModBlocks.STRIPPED_MANGROVE_LOG_SLAB, Blocks.STRIPPED_MANGROVE_LOG),
            new Pair<>(ModBlocks.STRIPPED_CHERRY_LOG_SLAB, Blocks.STRIPPED_CHERRY_LOG),
            new Pair<>(ModBlocks.STRIPPED_BAMBOO_SLAB, Blocks.STRIPPED_BAMBOO_BLOCK),
            new Pair<>(ModBlocks.STRIPPED_CRIMSON_STEM_SLAB, Blocks.STRIPPED_CRIMSON_STEM),
            new Pair<>(ModBlocks.STRIPPED_WARPED_STEM_SLAB, Blocks.STRIPPED_WARPED_STEM),
            new Pair<>(ModBlocks.STRIPPED_OAK_WOOD_SLAB, Blocks.STRIPPED_OAK_WOOD),
            new Pair<>(ModBlocks.STRIPPED_SPRUCE_WOOD_SLAB, Blocks.STRIPPED_SPRUCE_WOOD),
            new Pair<>(ModBlocks.STRIPPED_BIRCH_WOOD_SLAB, Blocks.STRIPPED_BIRCH_WOOD),
            new Pair<>(ModBlocks.STRIPPED_JUNGLE_WOOD_SLAB, Blocks.STRIPPED_JUNGLE_WOOD),
            new Pair<>(ModBlocks.STRIPPED_ACACIA_WOOD_SLAB, Blocks.STRIPPED_ACACIA_WOOD),
            new Pair<>(ModBlocks.STRIPPED_DARK_OAK_WOOD_SLAB, Blocks.STRIPPED_DARK_OAK_WOOD),
            new Pair<>(ModBlocks.STRIPPED_MANGROVE_WOOD_SLAB, Blocks.STRIPPED_MANGROVE_WOOD),
            new Pair<>(ModBlocks.STRIPPED_CHERRY_WOOD_SLAB, Blocks.STRIPPED_CHERRY_WOOD),
            new Pair<>(ModBlocks.STRIPPED_CRIMSON_HYPHAE_SLAB, Blocks.STRIPPED_CRIMSON_HYPHAE),
            new Pair<>(ModBlocks.STRIPPED_WARPED_HYPHAE_SLAB, Blocks.STRIPPED_WARPED_HYPHAE),
            new Pair<>(ModBlocks.CRACKED_STONE_BRICK_SLAB, Blocks.CRACKED_STONE_BRICKS),
            new Pair<>(ModBlocks.DEEPSLATE_SLAB, Blocks.DEEPSLATE),
            new Pair<>(ModBlocks.CRACKED_DEEPSLATE_BRICK_SLAB, Blocks.CRACKED_DEEPSLATE_BRICKS),
            new Pair<>(ModBlocks.REINFORCED_DEEPSLATE_SLAB, Blocks.REINFORCED_DEEPSLATE),
            new Pair<>(ModBlocks.PACKED_MUD_SLAB, Blocks.PACKED_MUD),
            new Pair<>(ModBlocks.NETHERRACK_SLAB, Blocks.NETHERRACK),
            new Pair<>(ModBlocks.CRACKED_NETHER_BRICK_SLAB, Blocks.CRACKED_NETHER_BRICKS),
            new Pair<>(ModBlocks.BASALT_SLAB, Blocks.BASALT),
            new Pair<>(ModBlocks.SMOOTH_BASALT_SLAB, Blocks.SMOOTH_BASALT),
            new Pair<>(ModBlocks.POLISHED_BASALT_SLAB, Blocks.POLISHED_BASALT),
            new Pair<>(ModBlocks.GILDED_BLACKSTONE_SLAB, Blocks.GILDED_BLACKSTONE),
            new Pair<>(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB, Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS),
            new Pair<>(ModBlocks.END_STONE_SLAB, Blocks.END_STONE),
            new Pair<>(ModBlocks.PURPUR_PILLAR_SLAB, Blocks.PURPUR_PILLAR),
            new Pair<>(ModBlocks.QUARTZ_BRICK_SLAB, Blocks.QUARTZ_BRICKS),
            new Pair<>(ModBlocks.QUARTZ_PILLAR_SLAB, Blocks.QUARTZ_PILLAR),
            new Pair<>(ModBlocks.AMETHYST_SLAB, Blocks.AMETHYST_BLOCK),
            new Pair<>(ModBlocks.WHITE_WOOL_SLAB, Blocks.WHITE_WOOL),
            new Pair<>(ModBlocks.LIGHT_GRAY_WOOL_SLAB, Blocks.LIGHT_GRAY_WOOL),
            new Pair<>(ModBlocks.GRAY_WOOL_SLAB, Blocks.GRAY_WOOL),
            new Pair<>(ModBlocks.BLACK_WOOL_SLAB, Blocks.BLACK_WOOL),
            new Pair<>(ModBlocks.BROWN_WOOL_SLAB, Blocks.BROWN_WOOL),
            new Pair<>(ModBlocks.RED_WOOL_SLAB, Blocks.RED_WOOL),
            new Pair<>(ModBlocks.ORANGE_WOOL_SLAB, Blocks.ORANGE_WOOL),
            new Pair<>(ModBlocks.YELLOW_WOOL_SLAB, Blocks.YELLOW_WOOL),
            new Pair<>(ModBlocks.LIME_WOOL_SLAB, Blocks.LIME_WOOL),
            new Pair<>(ModBlocks.GREEN_WOOL_SLAB, Blocks.GREEN_WOOL),
            new Pair<>(ModBlocks.CYAN_WOOL_SLAB, Blocks.CYAN_WOOL),
            new Pair<>(ModBlocks.LIGHT_BLUE_WOOL_SLAB, Blocks.LIGHT_BLUE_WOOL),
            new Pair<>(ModBlocks.BLUE_WOOL_SLAB, Blocks.BLUE_WOOL),
            new Pair<>(ModBlocks.PURPLE_WOOL_SLAB, Blocks.PURPLE_WOOL),
            new Pair<>(ModBlocks.MAGENTA_WOOL_SLAB, Blocks.MAGENTA_WOOL),
            new Pair<>(ModBlocks.PINK_WOOL_SLAB, Blocks.PINK_WOOL),
            new Pair<>(ModBlocks.TERRACOTTA_SLAB, Blocks.TERRACOTTA),
            new Pair<>(ModBlocks.WHITE_TERRACOTTA_SLAB, Blocks.WHITE_TERRACOTTA),
            new Pair<>(ModBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, Blocks.LIGHT_GRAY_TERRACOTTA),
            new Pair<>(ModBlocks.GRAY_TERRACOTTA_SLAB, Blocks.GRAY_TERRACOTTA),
            new Pair<>(ModBlocks.BLACK_TERRACOTTA_SLAB, Blocks.BLACK_TERRACOTTA),
            new Pair<>(ModBlocks.BROWN_TERRACOTTA_SLAB, Blocks.BROWN_TERRACOTTA),
            new Pair<>(ModBlocks.RED_TERRACOTTA_SLAB, Blocks.RED_TERRACOTTA),
            new Pair<>(ModBlocks.ORANGE_TERRACOTTA_SLAB, Blocks.ORANGE_TERRACOTTA),
            new Pair<>(ModBlocks.YELLOW_TERRACOTTA_SLAB, Blocks.YELLOW_TERRACOTTA),
            new Pair<>(ModBlocks.LIME_TERRACOTTA_SLAB, Blocks.LIME_TERRACOTTA),
            new Pair<>(ModBlocks.GREEN_TERRACOTTA_SLAB, Blocks.GREEN_TERRACOTTA),
            new Pair<>(ModBlocks.CYAN_TERRACOTTA_SLAB, Blocks.CYAN_TERRACOTTA),
            new Pair<>(ModBlocks.LIGHT_BLUE_TERRACOTTA_SLAB, Blocks.LIGHT_BLUE_TERRACOTTA),
            new Pair<>(ModBlocks.BLUE_TERRACOTTA_SLAB, Blocks.BLUE_TERRACOTTA),
            new Pair<>(ModBlocks.PURPLE_TERRACOTTA_SLAB, Blocks.PURPLE_TERRACOTTA),
            new Pair<>(ModBlocks.MAGENTA_TERRACOTTA_SLAB, Blocks.MAGENTA_TERRACOTTA),
            new Pair<>(ModBlocks.PINK_TERRACOTTA_SLAB, Blocks.PINK_TERRACOTTA),
            new Pair<>(ModBlocks.WHITE_CONCRETE_SLAB, Blocks.WHITE_CONCRETE),
            new Pair<>(ModBlocks.LIGHT_GRAY_CONCRETE_SLAB, Blocks.LIGHT_GRAY_CONCRETE),
            new Pair<>(ModBlocks.GRAY_CONCRETE_SLAB, Blocks.GRAY_CONCRETE),
            new Pair<>(ModBlocks.BLACK_CONCRETE_SLAB, Blocks.BLACK_CONCRETE),
            new Pair<>(ModBlocks.BROWN_CONCRETE_SLAB, Blocks.BROWN_CONCRETE),
            new Pair<>(ModBlocks.RED_CONCRETE_SLAB, Blocks.RED_CONCRETE),
            new Pair<>(ModBlocks.ORANGE_CONCRETE_SLAB, Blocks.ORANGE_CONCRETE),
            new Pair<>(ModBlocks.YELLOW_CONCRETE_SLAB, Blocks.YELLOW_CONCRETE),
            new Pair<>(ModBlocks.LIME_CONCRETE_SLAB, Blocks.LIME_CONCRETE),
            new Pair<>(ModBlocks.GREEN_CONCRETE_SLAB, Blocks.GREEN_CONCRETE),
            new Pair<>(ModBlocks.CYAN_CONCRETE_SLAB, Blocks.CYAN_CONCRETE),
            new Pair<>(ModBlocks.LIGHT_BLUE_CONCRETE_SLAB, Blocks.LIGHT_BLUE_CONCRETE),
            new Pair<>(ModBlocks.BLUE_CONCRETE_SLAB, Blocks.BLUE_CONCRETE),
            new Pair<>(ModBlocks.PURPLE_CONCRETE_SLAB, Blocks.PURPLE_CONCRETE),
            new Pair<>(ModBlocks.MAGENTA_CONCRETE_SLAB, Blocks.MAGENTA_CONCRETE),
            new Pair<>(ModBlocks.PINK_CONCRETE_SLAB, Blocks.PINK_CONCRETE),
            new Pair<>(ModBlocks.WHITE_CONCRETE_POWDER_SLAB, Blocks.WHITE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.LIGHT_GRAY_CONCRETE_POWDER_SLAB, Blocks.LIGHT_GRAY_CONCRETE_POWDER),
            new Pair<>(ModBlocks.GRAY_CONCRETE_POWDER_SLAB, Blocks.GRAY_CONCRETE_POWDER),
            new Pair<>(ModBlocks.BLACK_CONCRETE_POWDER_SLAB, Blocks.BLACK_CONCRETE_POWDER),
            new Pair<>(ModBlocks.BROWN_CONCRETE_POWDER_SLAB, Blocks.BROWN_CONCRETE_POWDER),
            new Pair<>(ModBlocks.RED_CONCRETE_POWDER_SLAB, Blocks.RED_CONCRETE_POWDER),
            new Pair<>(ModBlocks.ORANGE_CONCRETE_POWDER_SLAB, Blocks.ORANGE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.YELLOW_CONCRETE_POWDER_SLAB, Blocks.YELLOW_CONCRETE_POWDER),
            new Pair<>(ModBlocks.LIME_CONCRETE_POWDER_SLAB, Blocks.LIME_CONCRETE_POWDER),
            new Pair<>(ModBlocks.GREEN_CONCRETE_POWDER_SLAB, Blocks.GREEN_CONCRETE_POWDER),
            new Pair<>(ModBlocks.CYAN_CONCRETE_POWDER_SLAB, Blocks.CYAN_CONCRETE_POWDER),
            new Pair<>(ModBlocks.LIGHT_BLUE_CONCRETE_POWDER_SLAB, Blocks.LIGHT_BLUE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.BLUE_CONCRETE_POWDER_SLAB, Blocks.BLUE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.PURPLE_CONCRETE_POWDER_SLAB, Blocks.PURPLE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.MAGENTA_CONCRETE_POWDER_SLAB, Blocks.MAGENTA_CONCRETE_POWDER),
            new Pair<>(ModBlocks.PINK_CONCRETE_POWDER_SLAB, Blocks.PINK_CONCRETE_POWDER),
            new Pair<>(ModBlocks.GLASS_SLAB, Blocks.GLASS),
            new Pair<>(ModBlocks.TINTED_GLASS_SLAB, Blocks.TINTED_GLASS),
            new Pair<>(ModBlocks.WHITE_STAINED_GLASS_SLAB, Blocks.WHITE_STAINED_GLASS),
            new Pair<>(ModBlocks.LIGHT_GRAY_STAINED_GLASS_SLAB, Blocks.LIGHT_GRAY_STAINED_GLASS),
            new Pair<>(ModBlocks.GRAY_STAINED_GLASS_SLAB, Blocks.GRAY_STAINED_GLASS),
            new Pair<>(ModBlocks.BLACK_STAINED_GLASS_SLAB, Blocks.BLACK_STAINED_GLASS),
            new Pair<>(ModBlocks.BROWN_STAINED_GLASS_SLAB, Blocks.BROWN_STAINED_GLASS),
            new Pair<>(ModBlocks.RED_STAINED_GLASS_SLAB, Blocks.RED_STAINED_GLASS),
            new Pair<>(ModBlocks.ORANGE_STAINED_GLASS_SLAB, Blocks.ORANGE_STAINED_GLASS),
            new Pair<>(ModBlocks.YELLOW_STAINED_GLASS_SLAB, Blocks.YELLOW_STAINED_GLASS),
            new Pair<>(ModBlocks.LIME_STAINED_GLASS_SLAB, Blocks.LIME_STAINED_GLASS),
            new Pair<>(ModBlocks.GREEN_STAINED_GLASS_SLAB, Blocks.GREEN_STAINED_GLASS),
            new Pair<>(ModBlocks.CYAN_STAINED_GLASS_SLAB, Blocks.CYAN_STAINED_GLASS),
            new Pair<>(ModBlocks.LIGHT_BLUE_STAINED_GLASS_SLAB, Blocks.LIGHT_BLUE_STAINED_GLASS),
            new Pair<>(ModBlocks.BLUE_STAINED_GLASS_SLAB, Blocks.BLUE_STAINED_GLASS),
            new Pair<>(ModBlocks.PURPLE_STAINED_GLASS_SLAB, Blocks.PURPLE_STAINED_GLASS),
            new Pair<>(ModBlocks.MAGENTA_STAINED_GLASS_SLAB, Blocks.MAGENTA_STAINED_GLASS),
            new Pair<>(ModBlocks.PINK_STAINED_GLASS_SLAB, Blocks.PINK_STAINED_GLASS),
            new Pair<>(ModBlocks.GRASS_SLAB, Blocks.GRASS_BLOCK),
            new Pair<>(ModBlocks.PODZOL_SLAB, Blocks.PODZOL),
            new Pair<>(ModBlocks.MYCELIUM_SLAB, Blocks.MYCELIUM),
            new Pair<>(ModBlocks.DIRT_SLAB, Blocks.DIRT),
            new Pair<>(ModBlocks.DIRT_PATH_SLAB, Blocks.DIRT_PATH),
            new Pair<>(ModBlocks.COARSE_DIRT_SLAB, Blocks.COARSE_DIRT),
            new Pair<>(ModBlocks.ROOTED_DIRT_SLAB, Blocks.ROOTED_DIRT),
            new Pair<>(ModBlocks.MUD_SLAB, Blocks.MUD),
            new Pair<>(ModBlocks.CLAY_SLAB, Blocks.CLAY),
            new Pair<>(ModBlocks.GRAVEL_SLAB, Blocks.GRAVEL),
            new Pair<>(ModBlocks.SAND_SLAB, Blocks.SAND),
            new Pair<>(ModBlocks.RED_SAND_SLAB, Blocks.RED_SAND),
            new Pair<>(ModBlocks.ICE_SLAB, Blocks.ICE),
            new Pair<>(ModBlocks.PACKED_ICE_SLAB, Blocks.PACKED_ICE),
            new Pair<>(ModBlocks.BLUE_ICE_SLAB, Blocks.BLUE_ICE),
            new Pair<>(ModBlocks.MOSS_SLAB, Blocks.MOSS_BLOCK),
            new Pair<>(ModBlocks.CALCITE_SLAB, Blocks.CALCITE),
            new Pair<>(ModBlocks.DRIPSTONE_SLAB, Blocks.DRIPSTONE_BLOCK),
            new Pair<>(ModBlocks.MAGMA_BLOCK_SLAB, Blocks.MAGMA_BLOCK),
            new Pair<>(ModBlocks.OBSIDIAN_SLAB, Blocks.OBSIDIAN),
            new Pair<>(ModBlocks.CRYING_OBSIDIAN_SLAB, Blocks.CRYING_OBSIDIAN),
            new Pair<>(ModBlocks.CRIMSON_NYLIUM_SLAB, Blocks.CRIMSON_NYLIUM),
            new Pair<>(ModBlocks.WARPED_NYLIUM_SLAB, Blocks.WARPED_NYLIUM),
            new Pair<>(ModBlocks.SOUL_SAND_SLAB, Blocks.SOUL_SAND),
            new Pair<>(ModBlocks.SOUL_SOIL_SLAB, Blocks.SOUL_SOIL),
            new Pair<>(ModBlocks.BONE_SLAB, Blocks.BONE_BLOCK),
            new Pair<>(ModBlocks.GLOWSTONE_SLAB, Blocks.GLOWSTONE),
            new Pair<>(ModBlocks.MANGROVE_ROOT_SLAB, Blocks.MANGROVE_ROOTS),
            new Pair<>(ModBlocks.MUDDY_MANGROVE_ROOT_SLAB, Blocks.MUDDY_MANGROVE_ROOTS),
            new Pair<>(ModBlocks.MUSHROOM_STEM_SLAB, Blocks.MUSHROOM_STEM),
            new Pair<>(ModBlocks.OAK_LEAF_SLAB, Blocks.OAK_LEAVES),
            new Pair<>(ModBlocks.SPRUCE_LEAF_SLAB, Blocks.SPRUCE_LEAVES),
            new Pair<>(ModBlocks.BIRCH_LEAF_SLAB, Blocks.BIRCH_LEAVES),
            new Pair<>(ModBlocks.JUNGLE_LEAF_SLAB, Blocks.JUNGLE_LEAVES),
            new Pair<>(ModBlocks.ACACIA_LEAF_SLAB, Blocks.ACACIA_LEAVES),
            new Pair<>(ModBlocks.DARK_OAK_LEAF_SLAB, Blocks.DARK_OAK_LEAVES),
            new Pair<>(ModBlocks.MANGROVE_LEAF_SLAB, Blocks.MANGROVE_LEAVES),
            new Pair<>(ModBlocks.CHERRY_LEAF_SLAB, Blocks.CHERRY_LEAVES),
            new Pair<>(ModBlocks.AZALEA_LEAF_SLAB, Blocks.AZALEA_LEAVES),
            new Pair<>(ModBlocks.FLOWERING_AZALEA_LEAF_SLAB, Blocks.FLOWERING_AZALEA_LEAVES),
            new Pair<>(ModBlocks.BROWN_MUSHROOM_SLAB, Blocks.BROWN_MUSHROOM),
            new Pair<>(ModBlocks.RED_MUSHROOM_SLAB, Blocks.RED_MUSHROOM),
            new Pair<>(ModBlocks.NETHER_WART_SLAB, Blocks.NETHER_WART_BLOCK),
            new Pair<>(ModBlocks.WARPED_WART_SLAB, Blocks.WARPED_WART_BLOCK),
            new Pair<>(ModBlocks.DRIED_KELP_SLAB, Blocks.DRIED_KELP_BLOCK),
            new Pair<>(ModBlocks.TUBE_CORAL_SLAB, Blocks.TUBE_CORAL),
            new Pair<>(ModBlocks.BRAIN_CORAL_SLAB, Blocks.BRAIN_CORAL),
            new Pair<>(ModBlocks.BUBBLE_CORAL_SLAB, Blocks.BUBBLE_CORAL),
            new Pair<>(ModBlocks.FIRE_CORAL_SLAB, Blocks.FIRE_CORAL),
            new Pair<>(ModBlocks.HORN_CORAL_SLAB, Blocks.HORN_CORAL),
            new Pair<>(ModBlocks.DEAD_TUBE_CORAL_SLAB, Blocks.DEAD_TUBE_CORAL),
            new Pair<>(ModBlocks.DEAD_BRAIN_CORAL_SLAB, Blocks.DEAD_BRAIN_CORAL),
            new Pair<>(ModBlocks.DEAD_BUBBLE_CORAL_SLAB, Blocks.DEAD_BUBBLE_CORAL),
            new Pair<>(ModBlocks.DEAD_FIRE_CORAL_SLAB, Blocks.DEAD_FIRE_CORAL),
            new Pair<>(ModBlocks.DEAD_HORN_CORAL_SLAB, Blocks.DEAD_HORN_CORAL),
            new Pair<>(ModBlocks.SPONGE_SLAB, Blocks.SPONGE),
            new Pair<>(ModBlocks.WET_SPONGE_SLAB, Blocks.WET_SPONGE),
            new Pair<>(ModBlocks.MELON_SLAB, Blocks.MELON),
            new Pair<>(ModBlocks.PUMPKIN_SLAB, Blocks.PUMPKIN),
            new Pair<>(ModBlocks.HAY_SLAB, Blocks.HAY_BLOCK),
            new Pair<>(ModBlocks.HONEYCOMB_SLAB, Blocks.HONEYCOMB_BLOCK),
            new Pair<>(ModBlocks.SCULK_SLAB, Blocks.SCULK)*/
    );

    List<Pair<ItemConvertible, ItemConvertible>> vertical_slabs = Arrays.asList(
            new Pair<>(ModBlocks.OAK_VERTICAL_SLAB, Blocks.OAK_PLANKS),
            new Pair<>(ModBlocks.SPRUCE_VERTICAL_SLAB, Blocks.SPRUCE_PLANKS),
            new Pair<>(ModBlocks.BIRCH_VERTICAL_SLAB, Blocks.BIRCH_PLANKS),
            new Pair<>(ModBlocks.JUNGLE_VERTICAL_SLAB, Blocks.JUNGLE_PLANKS),
            new Pair<>(ModBlocks.ACACIA_VERTICAL_SLAB, Blocks.ACACIA_PLANKS),
            new Pair<>(ModBlocks.DARK_OAK_VERTICAL_SLAB, Blocks.DARK_OAK_PLANKS),
            new Pair<>(ModBlocks.MANGROVE_VERTICAL_SLAB, Blocks.MANGROVE_PLANKS),
            new Pair<>(ModBlocks.CHERRY_VERTICAL_SLAB, Blocks.CHERRY_PLANKS),
            new Pair<>(ModBlocks.BAMBOO_VERTICAL_SLAB, Blocks.BAMBOO),
            new Pair<>(ModBlocks.BAMBOO_MOSAIC_VERTICAL_SLAB, Blocks.BAMBOO_MOSAIC),
            new Pair<>(ModBlocks.CRIMSON_VERTICAL_SLAB, Blocks.CRIMSON_PLANKS),
            new Pair<>(ModBlocks.WARPED_VERTICAL_SLAB, Blocks.WARPED_PLANKS),
            new Pair<>(ModBlocks.OAK_LOG_VERTICAL_SLAB, Blocks.OAK_LOG),
            new Pair<>(ModBlocks.SPRUCE_LOG_VERTICAL_SLAB, Blocks.SPRUCE_LOG),
            new Pair<>(ModBlocks.BIRCH_LOG_VERTICAL_SLAB, Blocks.BIRCH_LOG),
            new Pair<>(ModBlocks.JUNGLE_LOG_VERTICAL_SLAB, Blocks.JUNGLE_LOG),
            new Pair<>(ModBlocks.ACACIA_LOG_VERTICAL_SLAB, Blocks.ACACIA_LOG),
            new Pair<>(ModBlocks.DARK_OAK_LOG_VERTICAL_SLAB, Blocks.DARK_OAK_LOG),
            new Pair<>(ModBlocks.MANGROVE_LOG_VERTICAL_SLAB, Blocks.MANGROVE_LOG),
            new Pair<>(ModBlocks.CHERRY_LOG_VERTICAL_SLAB, Blocks.CHERRY_LOG),
            new Pair<>(ModBlocks.BAMBOO_BLOCK_VERTICAL_SLAB, Blocks.BAMBOO_BLOCK),
            new Pair<>(ModBlocks.CRIMSON_STEM_VERTICAL_SLAB, Blocks.CRIMSON_STEM),
            new Pair<>(ModBlocks.WARPED_STEM_VERTICAL_SLAB, Blocks.WARPED_STEM),
            new Pair<>(ModBlocks.OAK_WOOD_VERTICAL_SLAB, Blocks.OAK_WOOD),
            new Pair<>(ModBlocks.SPRUCE_WOOD_VERTICAL_SLAB, Blocks.SPRUCE_WOOD),
            new Pair<>(ModBlocks.BIRCH_WOOD_VERTICAL_SLAB, Blocks.BIRCH_WOOD),
            new Pair<>(ModBlocks.JUNGLE_WOOD_VERTICAL_SLAB, Blocks.JUNGLE_WOOD),
            new Pair<>(ModBlocks.ACACIA_WOOD_VERTICAL_SLAB, Blocks.ACACIA_WOOD),
            new Pair<>(ModBlocks.DARK_OAK_WOOD_VERTICAL_SLAB, Blocks.DARK_OAK_WOOD),
            new Pair<>(ModBlocks.MANGROVE_WOOD_VERTICAL_SLAB, Blocks.MANGROVE_WOOD),
            new Pair<>(ModBlocks.CHERRY_WOOD_VERTICAL_SLAB, Blocks.CHERRY_WOOD),
            new Pair<>(ModBlocks.CRIMSON_HYPHAE_VERTICAL_SLAB, Blocks.CRIMSON_HYPHAE),
            new Pair<>(ModBlocks.WARPED_HYPHAE_VERTICAL_SLAB, Blocks.WARPED_HYPHAE),
            new Pair<>(ModBlocks.STRIPPED_OAK_LOG_VERTICAL_SLAB, Blocks.STRIPPED_OAK_LOG),
            new Pair<>(ModBlocks.STRIPPED_SPRUCE_LOG_VERTICAL_SLAB, Blocks.STRIPPED_SPRUCE_LOG),
            new Pair<>(ModBlocks.STRIPPED_BIRCH_LOG_VERTICAL_SLAB, Blocks.STRIPPED_BIRCH_LOG),
            new Pair<>(ModBlocks.STRIPPED_JUNGLE_LOG_VERTICAL_SLAB, Blocks.STRIPPED_JUNGLE_LOG),
            new Pair<>(ModBlocks.STRIPPED_ACACIA_LOG_VERTICAL_SLAB, Blocks.STRIPPED_ACACIA_LOG),
            new Pair<>(ModBlocks.STRIPPED_DARK_OAK_LOG_VERTICAL_SLAB, Blocks.STRIPPED_DARK_OAK_LOG),
            new Pair<>(ModBlocks.STRIPPED_MANGROVE_LOG_VERTICAL_SLAB, Blocks.STRIPPED_MANGROVE_LOG),
            new Pair<>(ModBlocks.STRIPPED_CHERRY_LOG_VERTICAL_SLAB, Blocks.STRIPPED_CHERRY_LOG),
            new Pair<>(ModBlocks.STRIPPED_BAMBOO_VERTICAL_SLAB, Blocks.STRIPPED_BAMBOO_BLOCK),
            new Pair<>(ModBlocks.STRIPPED_CRIMSON_STEM_VERTICAL_SLAB, Blocks.STRIPPED_CRIMSON_STEM),
            new Pair<>(ModBlocks.STRIPPED_WARPED_STEM_VERTICAL_SLAB, Blocks.STRIPPED_WARPED_STEM),
            new Pair<>(ModBlocks.STRIPPED_OAK_WOOD_VERTICAL_SLAB, Blocks.STRIPPED_OAK_WOOD),
            new Pair<>(ModBlocks.STRIPPED_SPRUCE_WOOD_VERTICAL_SLAB, Blocks.STRIPPED_SPRUCE_WOOD),
            new Pair<>(ModBlocks.STRIPPED_BIRCH_WOOD_VERTICAL_SLAB, Blocks.STRIPPED_BIRCH_WOOD),
            new Pair<>(ModBlocks.STRIPPED_JUNGLE_WOOD_VERTICAL_SLAB, Blocks.STRIPPED_JUNGLE_WOOD),
            new Pair<>(ModBlocks.STRIPPED_ACACIA_WOOD_VERTICAL_SLAB, Blocks.STRIPPED_ACACIA_WOOD),
            new Pair<>(ModBlocks.STRIPPED_DARK_OAK_WOOD_VERTICAL_SLAB, Blocks.STRIPPED_DARK_OAK_WOOD),
            new Pair<>(ModBlocks.STRIPPED_MANGROVE_WOOD_VERTICAL_SLAB, Blocks.STRIPPED_MANGROVE_WOOD),
            new Pair<>(ModBlocks.STRIPPED_CHERRY_WOOD_VERTICAL_SLAB, Blocks.STRIPPED_CHERRY_WOOD),
            new Pair<>(ModBlocks.STRIPPED_CRIMSON_HYPHAE_VERTICAL_SLAB, Blocks.STRIPPED_CRIMSON_HYPHAE),
            new Pair<>(ModBlocks.STRIPPED_WARPED_HYPHAE_VERTICAL_SLAB, Blocks.STRIPPED_WARPED_HYPHAE),
            new Pair<>(ModBlocks.STONE_VERTICAL_SLAB, Blocks.STONE),
            new Pair<>(ModBlocks.COBBLESTONE_VERTICAL_SLAB, Blocks.COBBLESTONE),
            new Pair<>(ModBlocks.MOSSY_COBBLESTONE_VERTICAL_SLAB, Blocks.MOSSY_COBBLESTONE),
            new Pair<>(ModBlocks.SMOOTH_STONE_VERTICAL_SLAB, Blocks.SMOOTH_STONE),
            new Pair<>(ModBlocks.STONE_BRICK_VERTICAL_SLAB, Blocks.STONE_BRICKS),
            new Pair<>(ModBlocks.CRACKED_STONE_BRICK_VERTICAL_SLAB, Blocks.CRACKED_STONE_BRICKS),
            new Pair<>(ModBlocks.MOSSY_STONE_BRICK_VERTICAL_SLAB, Blocks.MOSSY_STONE_BRICKS),
            new Pair<>(ModBlocks.GRANITE_VERTICAL_SLAB, Blocks.GRANITE),
            new Pair<>(ModBlocks.POLISHED_GRANITE_VERTICAL_SLAB, Blocks.POLISHED_GRANITE),
            new Pair<>(ModBlocks.DIORITE_VERTICAL_SLAB, Blocks.DIORITE),
            new Pair<>(ModBlocks.POLISHED_DIORITE_VERTICAL_SLAB, Blocks.POLISHED_DIORITE),
            new Pair<>(ModBlocks.ANDESITE_VERTICAL_SLAB, Blocks.ANDESITE),
            new Pair<>(ModBlocks.POLISHED_ANDESITE_VERTICAL_SLAB, Blocks.POLISHED_ANDESITE),
            new Pair<>(ModBlocks.DEEPSLATE_VERTICAL_SLAB, Blocks.DEEPSLATE),
            new Pair<>(ModBlocks.COBBLED_DEEPSLATE_VERTICAL_SLAB, Blocks.COBBLED_DEEPSLATE),
            new Pair<>(ModBlocks.POLISHED_DEEPSLATE_VERTICAL_SLAB, Blocks.POLISHED_DEEPSLATE),
            new Pair<>(ModBlocks.DEEPSLATE_BRICK_VERTICAL_SLAB, Blocks.DEEPSLATE_BRICKS),
            new Pair<>(ModBlocks.CRACKED_DEEPSLATE_BRICK_VERTICAL_SLAB, Blocks.CRACKED_DEEPSLATE_BRICKS),
            new Pair<>(ModBlocks.DEEPSLATE_TILE_VERTICAL_SLAB, Blocks.DEEPSLATE_TILES),
            new Pair<>(ModBlocks.REINFORCED_DEEPSLATE_VERTICAL_SLAB, Blocks.REINFORCED_DEEPSLATE),
            new Pair<>(ModBlocks.TUFF_VERTICAL_SLAB, Blocks.TUFF),
            new Pair<>(ModBlocks.POLISHED_TUFF_VERTICAL_SLAB, Blocks.POLISHED_TUFF),
            new Pair<>(ModBlocks.TUFF_BRICK_VERTICAL_SLAB, Blocks.TUFF_BRICKS),
            new Pair<>(ModBlocks.BRICK_VERTICAL_SLAB, Blocks.BRICKS),
            new Pair<>(ModBlocks.PACKED_MUD_VERTICAL_SLAB, Blocks.PACKED_MUD),
            new Pair<>(ModBlocks.MUD_BRICK_VERTICAL_SLAB, Blocks.MUD_BRICKS),
            new Pair<>(ModBlocks.SANDSTONE_VERTICAL_SLAB, Blocks.SANDSTONE),
            new Pair<>(ModBlocks.SMOOTH_SANDSTONE_VERTICAL_SLAB, Blocks.SMOOTH_SANDSTONE),
            new Pair<>(ModBlocks.CUT_SANDSTONE_VERTICAL_SLAB, Blocks.CUT_SANDSTONE),
            new Pair<>(ModBlocks.RED_SANDSTONE_VERTICAL_SLAB, Blocks.RED_SANDSTONE),
            new Pair<>(ModBlocks.SMOOTH_RED_SANDSTONE_VERTICAL_SLAB, Blocks.SMOOTH_RED_SANDSTONE),
            new Pair<>(ModBlocks.CUT_RED_SANDSTONE_VERTICAL_SLAB, Blocks.CUT_RED_SANDSTONE),
            new Pair<>(ModBlocks.PRISMARINE_VERTICAL_SLAB, Blocks.PRISMARINE),
            new Pair<>(ModBlocks.PRISMARINE_BRICK_VERTICAL_SLAB, Blocks.PRISMARINE_BRICKS),
            new Pair<>(ModBlocks.DARK_PRISMARINE_VERTICAL_SLAB, Blocks.DARK_PRISMARINE),
            new Pair<>(ModBlocks.NETHERRACK_VERTICAL_SLAB, Blocks.NETHERRACK),
            new Pair<>(ModBlocks.NETHER_BRICK_VERTICAL_SLAB, Blocks.NETHER_BRICKS),
            new Pair<>(ModBlocks.CRACKED_NETHER_BRICK_VERTICAL_SLAB, Blocks.CRACKED_NETHER_BRICKS),
            new Pair<>(ModBlocks.RED_NETHER_BRICK_VERTICAL_SLAB, Blocks.RED_NETHER_BRICKS),
            new Pair<>(ModBlocks.BASALT_VERTICAL_SLAB, Blocks.BASALT),
            new Pair<>(ModBlocks.SMOOTH_BASALT_VERTICAL_SLAB, Blocks.SMOOTH_BASALT),
            new Pair<>(ModBlocks.POLISHED_BASALT_VERTICAL_SLAB, Blocks.POLISHED_BASALT),
            new Pair<>(ModBlocks.BLACKSTONE_VERTICAL_SLAB, Blocks.BLACKSTONE),
            new Pair<>(ModBlocks.GILDED_BLACKSTONE_VERTICAL_SLAB, Blocks.GILDED_BLACKSTONE),
            new Pair<>(ModBlocks.POLISHED_BLACKSTONE_VERTICAL_SLAB, Blocks.POLISHED_BLACKSTONE),
            new Pair<>(ModBlocks.POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB, Blocks.POLISHED_BLACKSTONE_BRICKS),
            new Pair<>(ModBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_VERTICAL_SLAB, Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS),
            new Pair<>(ModBlocks.END_STONE_VERTICAL_SLAB, Blocks.END_STONE),
            new Pair<>(ModBlocks.END_STONE_BRICK_VERTICAL_SLAB, Blocks.END_STONE_BRICKS),
            new Pair<>(ModBlocks.PURPUR_VERTICAL_SLAB, Blocks.PURPUR_BLOCK),
            new Pair<>(ModBlocks.PURPUR_PILLAR_VERTICAL_SLAB, Blocks.PURPUR_PILLAR),
            new Pair<>(ModBlocks.QUARTZ_VERTICAL_SLAB, Blocks.QUARTZ_BLOCK),
            new Pair<>(ModBlocks.QUARTZ_BRICK_VERTICAL_SLAB, Blocks.QUARTZ_BRICKS),
            new Pair<>(ModBlocks.QUARTZ_PILLAR_VERTICAL_SLAB, Blocks.QUARTZ_PILLAR),
            new Pair<>(ModBlocks.SMOOTH_QUARTZ_VERTICAL_SLAB, Blocks.SMOOTH_QUARTZ),
            new Pair<>(ModBlocks.AMETHYST_VERTICAL_SLAB, Blocks.AMETHYST_BLOCK),
            new Pair<>(ModBlocks.CUT_COPPER_VERTICAL_SLAB, Blocks.CUT_COPPER),
            new Pair<>(ModBlocks.EXPOSED_CUT_COPPER_VERTICAL_SLAB, Blocks.EXPOSED_CUT_COPPER),
            new Pair<>(ModBlocks.WEATHERED_CUT_COPPER_VERTICAL_SLAB, Blocks.WEATHERED_CUT_COPPER),
            new Pair<>(ModBlocks.OXIDIZED_CUT_COPPER_VERTICAL_SLAB, Blocks.OXIDIZED_CUT_COPPER),
            new Pair<>(ModBlocks.WAXED_CUT_COPPER_VERTICAL_SLAB, Blocks.WAXED_CUT_COPPER),
            new Pair<>(ModBlocks.WAXED_EXPOSED_CUT_COPPER_VERTICAL_SLAB, Blocks.WAXED_EXPOSED_CUT_COPPER),
            new Pair<>(ModBlocks.WAXED_WEATHERED_CUT_COPPER_VERTICAL_SLAB, Blocks.WAXED_WEATHERED_CUT_COPPER),
            new Pair<>(ModBlocks.WAXED_OXIDIZED_CUT_COPPER_VERTICAL_SLAB, Blocks.WAXED_OXIDIZED_CUT_COPPER),
            //new Pair<>(ModBlocks.PETRIFIED_OAK_VERTICAL_SLAB, Blocks.PETRIFIED_OAK),
            new Pair<>(ModBlocks.WHITE_WOOL_VERTICAL_SLAB, Blocks.WHITE_WOOL),
            new Pair<>(ModBlocks.LIGHT_GRAY_WOOL_VERTICAL_SLAB, Blocks.LIGHT_GRAY_WOOL),
            new Pair<>(ModBlocks.GRAY_WOOL_VERTICAL_SLAB, Blocks.GRAY_WOOL),
            new Pair<>(ModBlocks.BLACK_WOOL_VERTICAL_SLAB, Blocks.BLACK_WOOL),
            new Pair<>(ModBlocks.BROWN_WOOL_VERTICAL_SLAB, Blocks.BROWN_WOOL),
            new Pair<>(ModBlocks.RED_WOOL_VERTICAL_SLAB, Blocks.RED_WOOL),
            new Pair<>(ModBlocks.ORANGE_WOOL_VERTICAL_SLAB, Blocks.ORANGE_WOOL),
            new Pair<>(ModBlocks.YELLOW_WOOL_VERTICAL_SLAB, Blocks.YELLOW_WOOL),
            new Pair<>(ModBlocks.LIME_WOOL_VERTICAL_SLAB, Blocks.LIME_WOOL),
            new Pair<>(ModBlocks.GREEN_WOOL_VERTICAL_SLAB, Blocks.GREEN_WOOL),
            new Pair<>(ModBlocks.CYAN_WOOL_VERTICAL_SLAB, Blocks.CYAN_WOOL),
            new Pair<>(ModBlocks.LIGHT_BLUE_WOOL_VERTICAL_SLAB, Blocks.LIGHT_BLUE_WOOL),
            new Pair<>(ModBlocks.BLUE_WOOL_VERTICAL_SLAB, Blocks.BLUE_WOOL),
            new Pair<>(ModBlocks.PURPLE_WOOL_VERTICAL_SLAB, Blocks.PURPLE_WOOL),
            new Pair<>(ModBlocks.MAGENTA_WOOL_VERTICAL_SLAB, Blocks.MAGENTA_WOOL),
            new Pair<>(ModBlocks.PINK_WOOL_VERTICAL_SLAB, Blocks.PINK_WOOL),
            new Pair<>(ModBlocks.TERRACOTTA_VERTICAL_SLAB, Blocks.TERRACOTTA),
            new Pair<>(ModBlocks.WHITE_TERRACOTTA_VERTICAL_SLAB, Blocks.WHITE_TERRACOTTA),
            new Pair<>(ModBlocks.LIGHT_GRAY_TERRACOTTA_VERTICAL_SLAB, Blocks.LIGHT_GRAY_TERRACOTTA),
            new Pair<>(ModBlocks.GRAY_TERRACOTTA_VERTICAL_SLAB, Blocks.GRAY_TERRACOTTA),
            new Pair<>(ModBlocks.BLACK_TERRACOTTA_VERTICAL_SLAB, Blocks.BLACK_TERRACOTTA),
            new Pair<>(ModBlocks.BROWN_TERRACOTTA_VERTICAL_SLAB, Blocks.BROWN_TERRACOTTA),
            new Pair<>(ModBlocks.RED_TERRACOTTA_VERTICAL_SLAB, Blocks.RED_TERRACOTTA),
            new Pair<>(ModBlocks.ORANGE_TERRACOTTA_VERTICAL_SLAB, Blocks.ORANGE_TERRACOTTA),
            new Pair<>(ModBlocks.YELLOW_TERRACOTTA_VERTICAL_SLAB, Blocks.YELLOW_TERRACOTTA),
            new Pair<>(ModBlocks.LIME_TERRACOTTA_VERTICAL_SLAB, Blocks.LIME_TERRACOTTA),
            new Pair<>(ModBlocks.GREEN_TERRACOTTA_VERTICAL_SLAB, Blocks.GREEN_TERRACOTTA),
            new Pair<>(ModBlocks.CYAN_TERRACOTTA_VERTICAL_SLAB, Blocks.CYAN_TERRACOTTA),
            new Pair<>(ModBlocks.LIGHT_BLUE_TERRACOTTA_VERTICAL_SLAB, Blocks.LIGHT_BLUE_TERRACOTTA),
            new Pair<>(ModBlocks.BLUE_TERRACOTTA_VERTICAL_SLAB, Blocks.BLUE_TERRACOTTA),
            new Pair<>(ModBlocks.PURPLE_TERRACOTTA_VERTICAL_SLAB, Blocks.PURPLE_TERRACOTTA),
            new Pair<>(ModBlocks.MAGENTA_TERRACOTTA_VERTICAL_SLAB, Blocks.MAGENTA_TERRACOTTA),
            new Pair<>(ModBlocks.PINK_TERRACOTTA_VERTICAL_SLAB, Blocks.PINK_TERRACOTTA),
            new Pair<>(ModBlocks.WHITE_CONCRETE_VERTICAL_SLAB, Blocks.WHITE_CONCRETE),
            new Pair<>(ModBlocks.LIGHT_GRAY_CONCRETE_VERTICAL_SLAB, Blocks.LIGHT_GRAY_CONCRETE),
            new Pair<>(ModBlocks.GRAY_CONCRETE_VERTICAL_SLAB, Blocks.GRAY_CONCRETE),
            new Pair<>(ModBlocks.BLACK_CONCRETE_VERTICAL_SLAB, Blocks.BLACK_CONCRETE),
            new Pair<>(ModBlocks.BROWN_CONCRETE_VERTICAL_SLAB, Blocks.BROWN_CONCRETE),
            new Pair<>(ModBlocks.RED_CONCRETE_VERTICAL_SLAB, Blocks.RED_CONCRETE),
            new Pair<>(ModBlocks.ORANGE_CONCRETE_VERTICAL_SLAB, Blocks.ORANGE_CONCRETE),
            new Pair<>(ModBlocks.YELLOW_CONCRETE_VERTICAL_SLAB, Blocks.YELLOW_CONCRETE),
            new Pair<>(ModBlocks.LIME_CONCRETE_VERTICAL_SLAB, Blocks.LIME_CONCRETE),
            new Pair<>(ModBlocks.GREEN_CONCRETE_VERTICAL_SLAB, Blocks.GREEN_CONCRETE),
            new Pair<>(ModBlocks.CYAN_CONCRETE_VERTICAL_SLAB, Blocks.CYAN_CONCRETE),
            new Pair<>(ModBlocks.LIGHT_BLUE_CONCRETE_VERTICAL_SLAB, Blocks.LIGHT_BLUE_CONCRETE),
            new Pair<>(ModBlocks.BLUE_CONCRETE_VERTICAL_SLAB, Blocks.BLUE_CONCRETE),
            new Pair<>(ModBlocks.PURPLE_CONCRETE_VERTICAL_SLAB, Blocks.PURPLE_CONCRETE),
            new Pair<>(ModBlocks.MAGENTA_CONCRETE_VERTICAL_SLAB, Blocks.MAGENTA_CONCRETE),
            new Pair<>(ModBlocks.PINK_CONCRETE_VERTICAL_SLAB, Blocks.PINK_CONCRETE),
            new Pair<>(ModBlocks.WHITE_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.WHITE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.LIGHT_GRAY_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.LIGHT_GRAY_CONCRETE_POWDER),
            new Pair<>(ModBlocks.GRAY_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.GRAY_CONCRETE_POWDER),
            new Pair<>(ModBlocks.BLACK_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.BLACK_CONCRETE_POWDER),
            new Pair<>(ModBlocks.BROWN_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.BROWN_CONCRETE_POWDER),
            new Pair<>(ModBlocks.RED_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.RED_CONCRETE_POWDER),
            new Pair<>(ModBlocks.ORANGE_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.ORANGE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.YELLOW_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.YELLOW_CONCRETE_POWDER),
            new Pair<>(ModBlocks.LIME_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.LIME_CONCRETE_POWDER),
            new Pair<>(ModBlocks.GREEN_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.GREEN_CONCRETE_POWDER),
            new Pair<>(ModBlocks.CYAN_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.CYAN_CONCRETE_POWDER),
            new Pair<>(ModBlocks.LIGHT_BLUE_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.LIGHT_BLUE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.BLUE_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.BLUE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.PURPLE_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.PURPLE_CONCRETE_POWDER),
            new Pair<>(ModBlocks.MAGENTA_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.MAGENTA_CONCRETE_POWDER),
            new Pair<>(ModBlocks.PINK_CONCRETE_POWDER_VERTICAL_SLAB, Blocks.PINK_CONCRETE_POWDER),
            new Pair<>(ModBlocks.GLASS_VERTICAL_SLAB, Blocks.GLASS),
            new Pair<>(ModBlocks.TINTED_GLASS_VERTICAL_SLAB, Blocks.TINTED_GLASS),
            new Pair<>(ModBlocks.WHITE_STAINED_GLASS_VERTICAL_SLAB, Blocks.WHITE_STAINED_GLASS),
            new Pair<>(ModBlocks.LIGHT_GRAY_STAINED_GLASS_VERTICAL_SLAB, Blocks.LIGHT_GRAY_STAINED_GLASS),
            new Pair<>(ModBlocks.GRAY_STAINED_GLASS_VERTICAL_SLAB, Blocks.GRAY_STAINED_GLASS),
            new Pair<>(ModBlocks.BLACK_STAINED_GLASS_VERTICAL_SLAB, Blocks.BLACK_STAINED_GLASS),
            new Pair<>(ModBlocks.BROWN_STAINED_GLASS_VERTICAL_SLAB, Blocks.BROWN_STAINED_GLASS),
            new Pair<>(ModBlocks.RED_STAINED_GLASS_VERTICAL_SLAB, Blocks.RED_STAINED_GLASS),
            new Pair<>(ModBlocks.ORANGE_STAINED_GLASS_VERTICAL_SLAB, Blocks.ORANGE_STAINED_GLASS),
            new Pair<>(ModBlocks.YELLOW_STAINED_GLASS_VERTICAL_SLAB, Blocks.YELLOW_STAINED_GLASS),
            new Pair<>(ModBlocks.LIME_STAINED_GLASS_VERTICAL_SLAB, Blocks.LIME_STAINED_GLASS),
            new Pair<>(ModBlocks.GREEN_STAINED_GLASS_VERTICAL_SLAB, Blocks.GREEN_STAINED_GLASS),
            new Pair<>(ModBlocks.CYAN_STAINED_GLASS_VERTICAL_SLAB, Blocks.CYAN_STAINED_GLASS),
            new Pair<>(ModBlocks.LIGHT_BLUE_STAINED_GLASS_VERTICAL_SLAB, Blocks.LIGHT_BLUE_STAINED_GLASS),
            new Pair<>(ModBlocks.BLUE_STAINED_GLASS_VERTICAL_SLAB, Blocks.BLUE_STAINED_GLASS),
            new Pair<>(ModBlocks.PURPLE_STAINED_GLASS_VERTICAL_SLAB, Blocks.PURPLE_STAINED_GLASS),
            new Pair<>(ModBlocks.MAGENTA_STAINED_GLASS_VERTICAL_SLAB, Blocks.MAGENTA_STAINED_GLASS),
            new Pair<>(ModBlocks.PINK_STAINED_GLASS_VERTICAL_SLAB, Blocks.PINK_STAINED_GLASS),
            new Pair<>(ModBlocks.GRASS_VERTICAL_SLAB, Blocks.GRASS_BLOCK),
            new Pair<>(ModBlocks.PODZOL_VERTICAL_SLAB, Blocks.PODZOL),
            new Pair<>(ModBlocks.MYCELIUM_VERTICAL_SLAB, Blocks.MYCELIUM),
            new Pair<>(ModBlocks.DIRT_VERTICAL_SLAB, Blocks.DIRT),
            new Pair<>(ModBlocks.DIRT_PATH_VERTICAL_SLAB, Blocks.DIRT_PATH),
            new Pair<>(ModBlocks.COARSE_DIRT_VERTICAL_SLAB, Blocks.COARSE_DIRT),
            new Pair<>(ModBlocks.ROOTED_DIRT_VERTICAL_SLAB, Blocks.ROOTED_DIRT),
            new Pair<>(ModBlocks.MUD_VERTICAL_SLAB, Blocks.MUD),
            new Pair<>(ModBlocks.CLAY_VERTICAL_SLAB, Blocks.CLAY),
            new Pair<>(ModBlocks.GRAVEL_VERTICAL_SLAB, Blocks.GRAVEL),
            new Pair<>(ModBlocks.SAND_VERTICAL_SLAB, Blocks.SAND),
            new Pair<>(ModBlocks.RED_SAND_VERTICAL_SLAB, Blocks.RED_SAND),
            new Pair<>(ModBlocks.ICE_VERTICAL_SLAB, Blocks.ICE),
            new Pair<>(ModBlocks.PACKED_ICE_VERTICAL_SLAB, Blocks.PACKED_ICE),
            new Pair<>(ModBlocks.BLUE_ICE_VERTICAL_SLAB, Blocks.BLUE_ICE),
            new Pair<>(ModBlocks.MOSS_VERTICAL_SLAB, Blocks.MOSS_BLOCK),
            new Pair<>(ModBlocks.CALCITE_VERTICAL_SLAB, Blocks.CALCITE),
            new Pair<>(ModBlocks.DRIPSTONE_VERTICAL_SLAB, Blocks.DRIPSTONE_BLOCK),
            new Pair<>(ModBlocks.MAGMA_BLOCK_VERTICAL_SLAB, Blocks.MAGMA_BLOCK),
            new Pair<>(ModBlocks.OBSIDIAN_VERTICAL_SLAB, Blocks.OBSIDIAN),
            new Pair<>(ModBlocks.CRYING_OBSIDIAN_VERTICAL_SLAB, Blocks.CRYING_OBSIDIAN),
            new Pair<>(ModBlocks.CRIMSON_NYLIUM_VERTICAL_SLAB, Blocks.CRIMSON_NYLIUM),
            new Pair<>(ModBlocks.WARPED_NYLIUM_VERTICAL_SLAB, Blocks.WARPED_NYLIUM),
            new Pair<>(ModBlocks.SOUL_SAND_VERTICAL_SLAB, Blocks.SOUL_SAND),
            new Pair<>(ModBlocks.SOUL_SOIL_VERTICAL_SLAB, Blocks.SOUL_SOIL),
            new Pair<>(ModBlocks.BONE_VERTICAL_SLAB, Blocks.BONE_BLOCK),
            new Pair<>(ModBlocks.GLOWSTONE_VERTICAL_SLAB, Blocks.GLOWSTONE),
            new Pair<>(ModBlocks.MANGROVE_ROOT_VERTICAL_SLAB, Blocks.MANGROVE_ROOTS),
            new Pair<>(ModBlocks.MUDDY_MANGROVE_ROOT_VERTICAL_SLAB, Blocks.MUDDY_MANGROVE_ROOTS),
            new Pair<>(ModBlocks.MUSHROOM_STEM_VERTICAL_SLAB, Blocks.MUSHROOM_STEM),
            new Pair<>(ModBlocks.OAK_LEAF_VERTICAL_SLAB, Blocks.OAK_LEAVES),
            new Pair<>(ModBlocks.SPRUCE_LEAF_VERTICAL_SLAB, Blocks.SPRUCE_LEAVES),
            new Pair<>(ModBlocks.BIRCH_LEAF_VERTICAL_SLAB, Blocks.BIRCH_LEAVES),
            new Pair<>(ModBlocks.JUNGLE_LEAF_VERTICAL_SLAB, Blocks.JUNGLE_LEAVES),
            new Pair<>(ModBlocks.ACACIA_LEAF_VERTICAL_SLAB, Blocks.ACACIA_LEAVES),
            new Pair<>(ModBlocks.DARK_OAK_LEAF_VERTICAL_SLAB, Blocks.DARK_OAK_LEAVES),
            new Pair<>(ModBlocks.MANGROVE_LEAF_VERTICAL_SLAB, Blocks.MANGROVE_LEAVES),
            new Pair<>(ModBlocks.CHERRY_LEAF_VERTICAL_SLAB, Blocks.CHERRY_LEAVES),
            new Pair<>(ModBlocks.AZALEA_LEAF_VERTICAL_SLAB, Blocks.AZALEA_LEAVES),
            new Pair<>(ModBlocks.FLOWERING_AZALEA_LEAF_VERTICAL_SLAB, Blocks.FLOWERING_AZALEA_LEAVES),
            new Pair<>(ModBlocks.BROWN_MUSHROOM_VERTICAL_SLAB, Blocks.BROWN_MUSHROOM),
            new Pair<>(ModBlocks.RED_MUSHROOM_VERTICAL_SLAB, Blocks.RED_MUSHROOM),
            new Pair<>(ModBlocks.NETHER_WART_VERTICAL_SLAB, Blocks.NETHER_WART_BLOCK),
            new Pair<>(ModBlocks.WARPED_WART_VERTICAL_SLAB, Blocks.WARPED_WART_BLOCK),
            new Pair<>(ModBlocks.DRIED_KELP_VERTICAL_SLAB, Blocks.DRIED_KELP_BLOCK),
            new Pair<>(ModBlocks.TUBE_CORAL_VERTICAL_SLAB, Blocks.TUBE_CORAL),
            new Pair<>(ModBlocks.BRAIN_CORAL_VERTICAL_SLAB, Blocks.BRAIN_CORAL),
            new Pair<>(ModBlocks.BUBBLE_CORAL_VERTICAL_SLAB, Blocks.BUBBLE_CORAL),
            new Pair<>(ModBlocks.FIRE_CORAL_VERTICAL_SLAB, Blocks.FIRE_CORAL),
            new Pair<>(ModBlocks.HORN_CORAL_VERTICAL_SLAB, Blocks.HORN_CORAL),
            new Pair<>(ModBlocks.DEAD_TUBE_CORAL_VERTICAL_SLAB, Blocks.DEAD_TUBE_CORAL),
            new Pair<>(ModBlocks.DEAD_BRAIN_CORAL_VERTICAL_SLAB, Blocks.DEAD_BRAIN_CORAL),
            new Pair<>(ModBlocks.DEAD_BUBBLE_CORAL_VERTICAL_SLAB, Blocks.DEAD_BUBBLE_CORAL),
            new Pair<>(ModBlocks.DEAD_FIRE_CORAL_VERTICAL_SLAB, Blocks.DEAD_FIRE_CORAL),
            new Pair<>(ModBlocks.DEAD_HORN_CORAL_VERTICAL_SLAB, Blocks.DEAD_HORN_CORAL),
            new Pair<>(ModBlocks.SPONGE_VERTICAL_SLAB, Blocks.SPONGE),
            new Pair<>(ModBlocks.WET_SPONGE_VERTICAL_SLAB, Blocks.WET_SPONGE),
            new Pair<>(ModBlocks.MELON_VERTICAL_SLAB, Blocks.MELON),
            new Pair<>(ModBlocks.PUMPKIN_VERTICAL_SLAB, Blocks.PUMPKIN),
            new Pair<>(ModBlocks.HAY_VERTICAL_SLAB, Blocks.HAY_BLOCK),
            new Pair<>(ModBlocks.HONEYCOMB_VERTICAL_SLAB, Blocks.HONEYCOMB_BLOCK),
            new Pair<>(ModBlocks.SCULK_VERTICAL_SLAB, Blocks.SCULK)
    );

    List<Pair<ItemConvertible, ItemConvertible>> vanilla_slabs = Arrays.asList(
            new Pair<>(Blocks.OAK_SLAB, Blocks.OAK_PLANKS),
            new Pair<>(Blocks.SPRUCE_SLAB, Blocks.SPRUCE_PLANKS),
            new Pair<>(Blocks.BIRCH_SLAB, Blocks.BIRCH_PLANKS),
            new Pair<>(Blocks.JUNGLE_SLAB, Blocks.JUNGLE_PLANKS),
            new Pair<>(Blocks.ACACIA_SLAB, Blocks.ACACIA_PLANKS),
            new Pair<>(Blocks.DARK_OAK_SLAB, Blocks.DARK_OAK_PLANKS),
            new Pair<>(Blocks.MANGROVE_SLAB, Blocks.MANGROVE_PLANKS),
            new Pair<>(Blocks.CHERRY_SLAB, Blocks.CHERRY_PLANKS),
            new Pair<>(Blocks.BAMBOO_SLAB, Blocks.BAMBOO_PLANKS),
            new Pair<>(Blocks.BAMBOO_MOSAIC_SLAB, Blocks.BAMBOO_MOSAIC),
            new Pair<>(Blocks.CRIMSON_SLAB, Blocks.CRIMSON_PLANKS),
            new Pair<>(Blocks.WARPED_SLAB, Blocks.WARPED_PLANKS),
            new Pair<>(Blocks.STONE_SLAB, Blocks.STONE),
            new Pair<>(Blocks.COBBLESTONE_SLAB, Blocks.COBBLESTONE),
            new Pair<>(Blocks.MOSSY_COBBLESTONE_SLAB, Blocks.MOSSY_COBBLESTONE),
            new Pair<>(Blocks.SMOOTH_STONE_SLAB, Blocks.SMOOTH_STONE),
            new Pair<>(Blocks.STONE_BRICK_SLAB, Blocks.STONE_BRICKS),
            new Pair<>(Blocks.MOSSY_STONE_BRICK_SLAB, Blocks.MOSSY_STONE_BRICKS),
            new Pair<>(Blocks.GRANITE_SLAB, Blocks.GRANITE),
            new Pair<>(Blocks.POLISHED_GRANITE_SLAB, Blocks.POLISHED_GRANITE),
            new Pair<>(Blocks.DIORITE_SLAB, Blocks.DIORITE),
            new Pair<>(Blocks.POLISHED_DIORITE_SLAB, Blocks.POLISHED_DIORITE),
            new Pair<>(Blocks.ANDESITE_SLAB, Blocks.ANDESITE),
            new Pair<>(Blocks.POLISHED_ANDESITE_SLAB, Blocks.POLISHED_ANDESITE),
            new Pair<>(Blocks.COBBLED_DEEPSLATE_SLAB, Blocks.COBBLED_DEEPSLATE),
            new Pair<>(Blocks.POLISHED_DEEPSLATE_SLAB, Blocks.POLISHED_DEEPSLATE),
            new Pair<>(Blocks.DEEPSLATE_BRICK_SLAB, Blocks.DEEPSLATE_BRICKS),
            new Pair<>(Blocks.DEEPSLATE_TILE_SLAB, Blocks.DEEPSLATE_TILES),
            new Pair<>(Blocks.TUFF_SLAB, Blocks.TUFF),
            new Pair<>(Blocks.POLISHED_TUFF_SLAB, Blocks.POLISHED_TUFF),
            new Pair<>(Blocks.TUFF_BRICK_SLAB, Blocks.TUFF_BRICKS),
            new Pair<>(Blocks.BRICK_SLAB, Blocks.BRICKS),
            new Pair<>(Blocks.MUD_BRICK_SLAB, Blocks.MUD_BRICKS),
            new Pair<>(Blocks.SANDSTONE_SLAB, Blocks.SANDSTONE),
            new Pair<>(Blocks.SMOOTH_SANDSTONE_SLAB, Blocks.SMOOTH_SANDSTONE),
            new Pair<>(Blocks.CUT_SANDSTONE_SLAB, Blocks.CUT_SANDSTONE),
            new Pair<>(Blocks.RED_SANDSTONE_SLAB, Blocks.RED_SANDSTONE),
            new Pair<>(Blocks.SMOOTH_RED_SANDSTONE_SLAB, Blocks.SMOOTH_RED_SANDSTONE),
            new Pair<>(Blocks.CUT_RED_SANDSTONE_SLAB, Blocks.CUT_RED_SANDSTONE),
            new Pair<>(Blocks.PRISMARINE_SLAB, Blocks.PRISMARINE),
            new Pair<>(Blocks.PRISMARINE_BRICK_SLAB, Blocks.PRISMARINE_BRICKS),
            new Pair<>(Blocks.DARK_PRISMARINE_SLAB, Blocks.DARK_PRISMARINE),
            new Pair<>(Blocks.NETHER_BRICK_SLAB, Blocks.NETHER_BRICKS),
            new Pair<>(Blocks.RED_NETHER_BRICK_SLAB, Blocks.RED_NETHER_BRICKS),
            new Pair<>(Blocks.BLACKSTONE_SLAB, Blocks.BLACKSTONE),
            new Pair<>(Blocks.POLISHED_BLACKSTONE_SLAB, Blocks.POLISHED_BLACKSTONE),
            new Pair<>(Blocks.POLISHED_BLACKSTONE_BRICK_SLAB, Blocks.POLISHED_BLACKSTONE_BRICKS),
            new Pair<>(Blocks.END_STONE_BRICK_SLAB, Blocks.END_STONE_BRICKS),
            new Pair<>(Blocks.PURPUR_SLAB, Blocks.PURPUR_BLOCK),
            new Pair<>(Blocks.QUARTZ_SLAB, Blocks.QUARTZ_BLOCK),
            new Pair<>(Blocks.SMOOTH_QUARTZ_SLAB, Blocks.SMOOTH_QUARTZ),
            new Pair<>(Blocks.CUT_COPPER_SLAB, Blocks.CUT_COPPER),
            new Pair<>(Blocks.EXPOSED_CUT_COPPER_SLAB, Blocks.EXPOSED_CUT_COPPER),
            new Pair<>(Blocks.WEATHERED_CUT_COPPER_SLAB, Blocks.WEATHERED_CUT_COPPER),
            new Pair<>(Blocks.OXIDIZED_CUT_COPPER_SLAB, Blocks.OXIDIZED_CUT_COPPER),
            new Pair<>(Blocks.WAXED_CUT_COPPER_SLAB, Blocks.WAXED_CUT_COPPER),
            new Pair<>(Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB, Blocks.WAXED_EXPOSED_CUT_COPPER),
            new Pair<>(Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB, Blocks.WAXED_WEATHERED_CUT_COPPER),
            new Pair<>(Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB, Blocks.WAXED_OXIDIZED_CUT_COPPER)
            //new Pair<>(Blocks.PETRIFIED_OAK_SLAB, Blocks.PETRIFIED_OAK)
    );

    public ModRecipeProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    @Override
    protected RecipeGenerator getRecipeGenerator(RegistryWrapper.WrapperLookup registryLookup, RecipeExporter exporter) {
        return new RecipeGenerator(registryLookup, exporter) {
            @Override
            public void generate() {
                RegistryWrapper.Impl<Item> itemLookup = registries.getOrThrow(RegistryKeys.ITEM);
            }
        };
    }

    //@Override
    public void generate(RecipeExporter exporter) {
        slabs(exporter);
        verticalSlabs(exporter);
        combineSlabs(exporter, slabs);
        combineVerticalSlabs(exporter);
        combineSlabs(exporter, vanilla_slabs);
    }

    private void slabs(RecipeExporter exporter) {
        for (Pair<ItemConvertible, ItemConvertible> recipe : slabs) {
            ItemConvertible slab = recipe.getFirst();
            ItemConvertible block = recipe.getSecond();
            ShapedRecipeJsonBuilder.create(null, RecipeCategory.BUILDING_BLOCKS, slab, 6)
                    .pattern("###")
                    .input('#', block)
                    .criterion(hasItem(block), conditionsFromPredicates((ItemPredicate.Builder) block))
                    .offerTo(exporter);
        }
    }

    private void verticalSlabs(RecipeExporter exporter) {
        for (Pair<ItemConvertible, ItemConvertible> recipe : vertical_slabs) {
            ItemConvertible slab = recipe.getFirst();
            ItemConvertible block = recipe.getSecond();
            ShapedRecipeJsonBuilder.create(null, RecipeCategory.BUILDING_BLOCKS, slab, 6)
                    .pattern("#")
                    .pattern("#")
                    .pattern("#")
                    .input('#', block)
                    .criterion(hasItem(block), conditionsFromPredicates((ItemPredicate.Builder) block))
                    .offerTo(exporter);
        }
    }

    private void combineSlabs(RecipeExporter exporter, List<Pair<ItemConvertible, ItemConvertible>> entries) {
        for (Pair<ItemConvertible, ItemConvertible> recipe : entries) {
            ItemConvertible slab = recipe.getFirst();
            ItemConvertible block = recipe.getSecond();
            String filePath = block.toString();
            filePath = filePath.substring((filePath.indexOf(":") + 1), filePath.indexOf("}")) + "_from_slab";
            ShapedRecipeJsonBuilder.create(null, RecipeCategory.BUILDING_BLOCKS, block, 1)
                    .pattern("#")
                    .pattern("#")
                    .input('#', slab)
                    .criterion(hasItem(slab), conditionsFromPredicates((ItemPredicate.Builder) slab))
                    .offerTo(exporter, String.valueOf(Identifier.of("slabee", filePath)));
        }
    }

    private void combineVerticalSlabs(RecipeExporter exporter) {
        for (Pair<ItemConvertible, ItemConvertible> recipe : vertical_slabs) {
            ItemConvertible slab = recipe.getFirst();
            ItemConvertible block = recipe.getSecond();
            String filePath = block.toString();
            filePath = filePath.substring((filePath.indexOf(":") + 1), filePath.indexOf("}")) + "_from_vertical_slab";
            ShapedRecipeJsonBuilder.create(null, RecipeCategory.BUILDING_BLOCKS, block, 1)
                    .pattern("##")
                    .input('#', slab)
                    .criterion(hasItem(slab), conditionsFromPredicates((ItemPredicate.Builder) slab))
                    .offerTo(exporter, String.valueOf(Identifier.of("slabee", filePath)));
        }
    }

    @Override
    public String getName() {
        return "Mattéo35";
    }
}